name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt install cmake libboost-filesystem-dev libboost-test-dev gcc
    - name: Build and Test
      run: |
          export CXX=g++
          export CC=gcc
          export CODECOV_TOKEN="c3d08772-6107-422c-886f-ada5c4780d5c"
          mkdir build && cd build
          cmake --version
          g++ --version
          cat /usr/include/boost/version.hpp
          cmake .. -DINOTIFY_GCC_COVERAGE=1
          cmake --build .
          ctest -VV
          bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
